# fly.toml app configuration file generated for dice-mat on 2023-12-27T15:53:09+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dice-mat"
primary_region = "ams"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    hard_limit = 100
    soft_limit = 75

  [[http_service.checks]]
    interval = "30s"
    timeout = "2s"
    grace_period = "1s"
    method = "GET"
    path = "/"

